### ISSUE TITLE
Unable to fully load games

### ISSUE THREAD

**Issue by 1101-trash** [Y8Games/Y8-Browser-releases#24]
I was trying to play SCGMD4 and it never loads:
![imagen](https://user-images.githubusercontent.com/50521056/218319424-f017b372-6fcf-4363-9698-6046ceae005d.png)
It's stuck at (let's say 99%) almost the end of the loading proccess.

This does not happens on other games that I've tested. It'd be also useful that i'm trying to play in arcadeprehacks. The rest of the games works perfectly.

Thanks you very much and congrats for your very good work of the browser!

**Comment by squeletoon27** [comment]
The game seems to be functional on my end, you should consider trying on yours, so we can make sure this issue is fixed.

**Comment by 1101-trash** [comment]
> The game seems to be functional on my end, you should consider trying on yours, so we can make sure this issue is fixed.

Still not working on mine. Maybe some malfuction on some component installed on it but I can't really guess. Thanks you anyway :)

Quick edit: have just seen on console that it's failed loading it cause the flash file of the game is loaded by non secure protocol while the browser is trying to load it with HTTPS. I just quickly fixed it loading the href location of the file with HTTP protocol.

**Comment by 1101-trash** [comment]
Sorry for reopen, the game loads but can't apply the hack to unlock levels. It may be any way to load it with the 'hacks' code injected or something.
EDIT: Loading the webpage with HTTP doesn't load the game either.
